### ISSUE TITLE
If no CI is matched, try Git

### ISSUE THREAD

**Issue by geelen** [bitgenics/fab-upload-cli#1]
At the moment, this expects that you're always running in a CI environment, but if you're testing from the command line, you end up pushing things on `unknown-branch`.

You can get the current branch from `git rev-parse --abbrev-ref HEAD`. That's probably a better fallback.

**Comment by plexey** [comment]
This should be fixed in version 0.2.2. 
The package will try to retrieve the branch from git prior to falling back to `unknown-branch`.
