### ISSUE TITLE
Check git dirty status

### ISSUE THREAD

**Issue by geelen** [bitgenics/fab-upload-cli#2]
Again, only really useful if you're doing this on the command line, but if `fab-upload` is using your last commit info, it should show a warning if there's uncommitted changes as it starts the build.

You probably don't want to throw an error since on CI, it might be possible for a previous step to dirty the repo, either by adding untracked files (like if you forget to `.gitignore` a file/dir because it's only ever produced on CI), or, less likely, touching a checked-in file.

So a warning that displays before the build starts, gives a human a while to see the error and kill the build before it's uploaded.

**Comment by plexey** [comment]
Prior to starting a build, version 0.2.2 now checks for uncommitted changes prior to starting the build. 
If uncommitted changes are detected, it will print a warning message and wait for 5 seconds.
